### ISSUE TITLE
Sleep not working in libxDot-Dev but works in libxDot

### ISSUE THREAD

**Issue by dsMartyn** [MultiTechSystems/libxDot-dev-mbed5#2]
using MBED 5.11.1 in Eclipse 4.9.0 with ARM GCC v6

When executing this code on the Production lib it works fine but using the latest dev lib 3.2.2-7 it locks up on _dot->sleep(...) 'test' never gets printed, the LED's flash and no debug context as the device is in asleep. 
Not sure what else i can try to find the issue.

main.cpp

```javascript
int main()
{
	mDot* _dot;
	lora::ChannelPlan* _plan; 

	mts::MTSLog::setLogLevel(mts::MTSLog::TRACE_LEVEL);

	_plan = new lora::ChannelPlan_EU868();
	_dot = mDot::getInstance(_plan);

	dotutil::sleep_save_io();
	dotutil::sleep_configure_io(_dot);

	_dot->sleep(1, mDot::RTC_ALARM, false); // sleep for 1 second

	dotutil::sleep_restore_io();
	printf("test\r\n");
}
```

mbed config --global GCC_ARM_PATH /Applications/MBEDCLI.app/Contents/Resources/gcc/gcc-arm-none-eabi-6-2017-q2-update/bin/
mbed new xdot
mbed add https://github.com/MultiTechSystems/libxDot-dev-mbed5
mbed -t toolchain GCC_ARM
< add main.c > 
mbed compile -m xdot_l151cc
mbed export -i gnuarmeclipse -m xdot_l151cc

Eclipse environment path for GCC_ARM_PATH needs to be set manually as mbed-cli doesn't seem to add it but should work without anything else changing

**Comment by reissjason** [comment]
Thank you for the report. We have also noticed this issue.
A fix should be pushed shortly.
